settings:
    servers:
        wandel:
            host: 0.0.0.0
            port: 1337
            wandel_1: "https://www.wandel-restaurant.de/restaurants/wandel-berlin-mitte.html"
            slack_token: ~
